- name: Configure machines for workstation use
  hosts: localhost
  tasks:
  - name: Write apt configuration
    become: true
    block:
    - name: Write apt sources.list
      ansible.builtin.copy:
        src: common/etc/apt/sources.list
        dest: /etc/apt
        owner: root
        mode: 0644
    - name: Write apt sources.list.d
      ansible.builtin.copy:
        src: workstation/etc/apt/sources.list.d
        dest: /etc/apt
        owner: root
        mode: 0755
    - name: Write apt keyring
      ansible.builtin.copy:
        src: workstation/etc/apt/keyrings
        dest: /etc/apt
        owner: root
        mode: 0755
    - name: Write apt preferences.d
      ansible.builtin.copy:
        src: workstation/etc/apt/preferences.d
        dest: /etc/apt
        owner: root
        mode: 0755
  - name: Enable multi-arch
    become: true
    ansible.builtin.command: dpkg --add-architecture i386
  - name: Update & upgrade
    become: true
    ansible.builtin.apt:
      update_cache: true
      upgrade: dist
  - name: Install updated kernel from stable-backports
    become: true
    ansible.builtin.apt:
      package: linux-image-amd64
      default_release: stable-backports
  - name: Install additional graphics libraries
    become: true
    ansible.builtin.apt:
      package:
      - mesa-vulkan-drivers
      - mesa-vulkan-drivers:i386
      - libglx-mesa0:i386
      - libgl1-mesa-dri:i386
  - name: Uninstall unnecessary apps
    become: true
    ansible.builtin.apt:
      package:
      - firefox-esr
      state: absent
  - name: Install apps
    become: true
    ansible.builtin.apt:
      package:
      - code
      - firefox
      - spotify-client
      - steam-installer
